name: SignGUI
version: 1.2.1
api-version: 1.19
description: SignGUI API for your Minecraft Bukkit plugins.
authors: [Cleymax, TheMiniLuca]
website: https://github.com/Cleymax/SignGUI
main: fr.cleymax.signgui.SignGUIPlugin
