name: SignGUI
version: 1.1.0
api-version: 1.17
description: SignGUI API for your Minecraft Bukkit plugins.
author: Cleymax
website: https://github.com/Cleymax/SignGUI
main: fr.cleymax.signgui.SignGUIPlugin
