name: Java CI

on: [push]

env:
  MC_VERSION: 1.19.2
  VERSION: 1.2.1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install Spigot with BuildTools
        shell: bash
        run: |
          curl -Lo BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev $MC_VERSION
      - name: Add Permission
        run: chmod +x ./gradlew
      - name: Clean, Build and generate Doc with Gradle
        run: ./gradlew clean build javadoc
      - name: Tar files
        shell: bash
        run: |
          tar -cvf "SignGUI-$VERSION-(MC-$MC_VERSION).tar" build/libs/*.jar docs/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: "SignGUI-$VERSION-(MC-$MC_VERSION).tar"
