name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install Spigot with BuildTools
        shell: bash
        run: |
          mkdir ./tmp
          popd ./tmp
          curl -Lo BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.19.2
          pushd
      - name: Add Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
