name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install Spigot with BuildTools
        shell: bash
        run: |
          curl -Lo BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.19.2
      - name: Add Permission
        run: chmod +x ./gradlew
      - name: Clean, Build and generate Doc with Gradle
        run: ./gradlew clean build javadoc
      - name: Tar files
        shell: bash
        run: |
          tar -cvf SignGUI-${GITHUB_REF##*/}.tar build/libs/*.jar docs/
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Build
          path: SignGUI-${GITHUB_REF##*/}.tar
